### ISSUE TITLE
Cannot Detect Proxy

### ISSUE THREAD

**Issue by venessiel** [xKakima/3D-Scripts#1]
Proxy group cannot be detected when inside a group. It's under OLD_models group.

**Comment by xKakima** [comment]
Thank you for letting the team know, we will fix is on the next patch

**Comment by venessiel** [comment]
Please make haste. Many thanks.
Hillary Bugayong

**Comment by xKakima** [comment]
This is updated with the latest commit, if issues persist kindly open this issue again.
